import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Xopcify | Playlists',
  description: 'Generated by create next app',
};

export default function Albums() {
  return (
    <div>
      <h3>Playlists page</h3>
    </div>
  );
}
