import { Metadata } from 'next';
import tr from '../tracks.module.scss';

export const metadata: Metadata = {
  title: 'Xopcify | Tracks',
  description: 'Generated by create next app',
};

export default function Tracks() {
  return (
    <div>
      <div className={tr.container}>
        <div className={tr.tracks__title}>
          <h3>Create | Add new track</h3>
        </div>
        <div className={tr.create_button__item}>
          <div></div>
          <button className={tr.create__button}>Create</button>
        </div>
      </div>
    </div>
  );
}
