'use client';

import { CssBaseline, ThemeProvider, createTheme } from '@mui/material';
import Navbar from '../components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import Player from '@/components/Player';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Xopcify',
  description: 'Generated by create next app',
};

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={darkTheme}>
          <CssBaseline />
          <Navbar />
          <main>{children}</main>
          <Player />
        </ThemeProvider>
      </body>
    </html>
  );
}
