'use client';
import { Metadata } from 'next';
import tr from './tracks.module.scss';
import { useRouter } from 'next/navigation';
import { ITrack } from '@/types/track';
import TrackList from '@/components/TrackList';

export const metadata: Metadata = {
  title: 'Xopcify | Tracks',
  description: 'Generated by create next app',
};

export default function Tracks() {
  const router = useRouter();
  const tracks: ITrack[] = [
    {
      _id: '1',
      name: 'Проза к JavaScript',
      artist: 'Artem Xopc',
      text: 'Текст песни',
      listens: 42,
      picture: '',
      audio: '',
      comments: [],
    },
    {
      _id: '2',
      name: 'Проза к TypeScript',
      artist: 'Artem Xopc',
      text: 'Текст песни',
      listens: 42,
      picture: '',
      audio: '',
      comments: [],
    },
    {
      _id: '3',
      name: 'Проза к Python',
      artist: 'Artem Xopc',
      text: 'Текст песни',
      listens: 42,
      picture: '',
      audio: '',
      comments: [],
    },
  ];
  return (
    <div>
      <div className={tr.container}>
        <div className={tr.box}>
          <div className={tr.tracks__title}>
            <h3>Track list</h3>
          </div>
          <div className={tr.create_button__item}>
            <div></div>
            <button className={tr.create__button} onClick={() => router.push('/tracks/create')}>
              Create
            </button>
          </div>
          <TrackList tracks={tracks} />
        </div>
      </div>
    </div>
  );
}
