'use client';
import { Metadata } from 'next';
import tr from './tracks.module.scss';
import { useRouter } from 'next/navigation';
import { ITrack } from '@/types/track';
import TrackList from '@/components/TrackList';

import ava1 from '../assets/image/1.jpg';

export const metadata: Metadata = {
  title: 'Xopcify | Tracks',
  description: 'Generated by create next app',
};

export default function Tracks() {
  const router = useRouter();
  const tracks: ITrack[] = [
    {
      _id: '1',
      name: 'Two Moons',
      artist: 'Bobby Richards',
      text: 'Текст песни',
      listens: 42,
      picture: 'http://localhost:5000/picture/e60e2a6b-7329-4482-af38-5fba3906563f.jpg',
      audio: 'audio/6835743c-936b-4fbb-9e3f-c53133927ec5.mp3',
      comments: [],
    },
    {
      _id: '2',
      name: 'Silent Moon',
      artist: 'John Williams',
      text: 'Текст песни',
      listens: 42,
      picture: 'http://localhost:5000/picture/2c9d876f-79af-4862-82fd-93f6960ae5c2.jpg',
      audio: 'http://localhost:5000/audio/10d4b2a6-2f5f-44ff-aeb9-9d71d7374b5a.mp3',
      comments: [],
    },
    {
      _id: '3',
      name: 'Проза к TypeScript',
      artist: 'Artem Xopc',
      text: 'Текст песни',
      listens: 42,
      picture: '',
      audio: '',
      comments: [],
    },
  ];
  return (
    <div>
      <div className={tr.container}>
        <div className={tr.box}>
          <div className={tr.tracks__title}>
            <h3>Track list</h3>
          </div>
          <div className={tr.create_button__item}>
            <div></div>
            <button className={tr.create__button} onClick={() => router.push('/tracks/create')}>
              Create
            </button>
          </div>
          <TrackList tracks={tracks} />
        </div>
      </div>
    </div>
  );
}
